// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
//import 'firebase_options.dart';

/// // ...
// await Firebase.initializeApp(
//   options = DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKDtEmyD_gZcpL2Z9jeZeNNvbpA1oB6G8',
    appId: '1:692448064694:web:e3a012880a0f34b2f1e217',
    messagingSenderId: '692448064694',
    projectId: 'localtest1-6b448',
    authDomain: 'localtest1-6b448.firebaseapp.com',
    storageBucket: 'localtest1-6b448.appspot.com',
    measurementId: 'G-QZC7TWTE3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4EjPXSa5Y6hc5qFSwBxInZWjxhvgiaMk',
    appId: '1:692448064694:android:957e981e618498def1e217',
    messagingSenderId: '692448064694',
    projectId: 'localtest1-6b448',
    storageBucket: 'localtest1-6b448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsgkabP4qeuoiu5CK9PjhRXxoRhIhXF5w',
    appId: '1:692448064694:ios:fb8352c559f8a9edf1e217',
    messagingSenderId: '692448064694',
    projectId: 'localtest1-6b448',
    storageBucket: 'localtest1-6b448.appspot.com',
    iosClientId:
        '692448064694-oma2au3ftl02lbusbc8h5fkvg8qe5our.apps.googleusercontent.com',
    iosBundleId: 'com.example.localtest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsgkabP4qeuoiu5CK9PjhRXxoRhIhXF5w',
    appId: '1:692448064694:ios:7a435afa7593d88af1e217',
    messagingSenderId: '692448064694',
    projectId: 'localtest1-6b448',
    storageBucket: 'localtest1-6b448.appspot.com',
    iosClientId:
        '692448064694-j5kgdu3jje3o5mkl90mluemopmv9l9gs.apps.googleusercontent.com',
    iosBundleId: 'com.example.localtest1.RunnerTests',
  );
}
